//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 05:12:53 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2000/09/xmldsig#",xmlns = {@XmlNs(prefix = "ds", namespaceURI = "http://www.w3.org/2000/09/xmldsig#")}, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hello.entity.org.w3._2000._09.xmldsig;

import javax.xml.bind.annotation.XmlNs;