//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 05:12:53 PM CEST 
//


package hello.entity.gov.gradskaskupstina;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for TAmandman complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAmandman">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PredmetIzmene" type="{http://www.gradskaskupstina.gov/}TReferenca"/>
 *         &lt;element name="TipIzmene" type="{http://www.gradskaskupstina.gov/}TTipIzmene"/>
 *         &lt;element name="Sadrzaj" type="{http://www.gradskaskupstina.gov/}TSemiStruktuiraniTekst" minOccurs="0"/>
 *         &lt;element name="Obrazlozenje" type="{http://www.gradskaskupstina.gov/}TSemiStruktuiraniTekst"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RedniBroj" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAmandman", propOrder = {
    "predmetIzmene",
    "tipIzmene",
    "sadrzaj",
    "obrazlozenje"
})
public class TAmandman {

    @XmlElement(name = "PredmetIzmene", required = true)
    protected TReferenca predmetIzmene;
    @XmlElement(name = "TipIzmene", required = true)
    protected TTipIzmene tipIzmene;
    @XmlElement(name = "Sadrzaj")
    protected String sadrzaj;
    @XmlElement(name = "Obrazlozenje", required = true)
    protected TSemiStruktuiraniTekst obrazlozenje;
    @XmlAttribute(name = "RedniBroj")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger redniBroj;

    /**
     * Gets the value of the predmetIzmene property.
     * 
     * @return
     *     possible object is
     *     {@link TReferenca }
     *     
     */
    public TReferenca getPredmetIzmene() {
        return predmetIzmene;
    }

    /**
     * Sets the value of the predmetIzmene property.
     * 
     * @param value
     *     allowed object is
     *     {@link TReferenca }
     *     
     */
    public void setPredmetIzmene(TReferenca value) {
        this.predmetIzmene = value;
    }

    /**
     * Gets the value of the tipIzmene property.
     * 
     * @return
     *     possible object is
     *     {@link TTipIzmene }
     *     
     */
    public TTipIzmene getTipIzmene() {
        return tipIzmene;
    }

    /**
     * Sets the value of the tipIzmene property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTipIzmene }
     *     
     */
    public void setTipIzmene(TTipIzmene value) {
        this.tipIzmene = value;
    }

    /**
     * Gets the value of the sadrzaj property.
     * 
     * @return
     *     possible object is
     *     {@link TSemiStruktuiraniTekst }
     *     
     */
    public String getSadrzaj() {
        return sadrzaj;
    }

    /**
     * Sets the value of the sadrzaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSemiStruktuiraniTekst }
     *     
     */
    public void setSadrzaj(String value) {
        this.sadrzaj = value;
    }

    /**
     * Gets the value of the obrazlozenje property.
     * 
     * @return
     *     possible object is
     *     {@link TSemiStruktuiraniTekst }
     *     
     */
    public TSemiStruktuiraniTekst getObrazlozenje() {
        return obrazlozenje;
    }

    /**
     * Sets the value of the obrazlozenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSemiStruktuiraniTekst }
     *     
     */
    public void setObrazlozenje(TSemiStruktuiraniTekst value) {
        this.obrazlozenje = value;
    }

    /**
     * Gets the value of the redniBroj property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRedniBroj() {
        return redniBroj;
    }

    /**
     * Sets the value of the redniBroj property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRedniBroj(BigInteger value) {
        this.redniBroj = value;
    }

}
