//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 05:11:41 PM CEST 
//


package hello.entity.gov.gradskaskupstina;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for TStav complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TStav">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="Tacka" type="{http://www.gradskaskupstina.gov/}TTacka" maxOccurs="unbounded" minOccurs="2"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="RedniBroj" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStav", propOrder = {
        "tekst",
        "tacka"
})
public class TStav {

    @XmlElement(name = "Tekst", required = true)
    protected String tekst;
    @XmlElement(name = "Tacka")
    protected List<TTacka> tacka;
    @XmlAttribute(name = "RedniBroj", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger redniBroj;

    /**
     * Gets the value of the tekst property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTekst() {
        return tekst;
    }

    /**
     * Sets the value of the tekst property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTekst(String value) {
        this.tekst = value;
    }

    /**
     * Gets the value of the tacka property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tacka property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTacka().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TTacka }
     *
     *
     */
    public List<TTacka> getTacka() {
        if (tacka == null) {
            tacka = new ArrayList<TTacka>();
        }
        return this.tacka;
    }

    /**
     * Gets the value of the redniBroj property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getRedniBroj() {
        return redniBroj;
    }

    /**
     * Sets the value of the redniBroj property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setRedniBroj(BigInteger value) {
        this.redniBroj = value;
    }

}