//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.24 at 06:27:21 PM CEST 
//


package gov.gradskaskupstina;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for TReferenca complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TReferenca">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attGroup ref="{http://www.gradskaskupstina.gov/}AGReferenca"/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TReferenca", propOrder = {
    "value"
})
public class TReferenca {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "ref_akt")
    protected String refAkt;
    @XmlAttribute(name = "ref_clanovi", required = true)
    protected String refClanovi;
    @XmlAttribute(name = "ref_stavovi")
    protected String refStavovi;
    @XmlAttribute(name = "ref_tacke")
    protected String refTacke;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the refAkt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefAkt() {
        if (refAkt == null) {
            return "ovaj_akt";
        } else {
            return refAkt;
        }
    }

    /**
     * Sets the value of the refAkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefAkt(String value) {
        this.refAkt = value;
    }

    /**
     * Gets the value of the refClanovi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefClanovi() {
        return refClanovi;
    }

    /**
     * Sets the value of the refClanovi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefClanovi(String value) {
        this.refClanovi = value;
    }

    /**
     * Gets the value of the refStavovi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefStavovi() {
        return refStavovi;
    }

    /**
     * Sets the value of the refStavovi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefStavovi(String value) {
        this.refStavovi = value;
    }

    /**
     * Gets the value of the refTacke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefTacke() {
        return refTacke;
    }

    /**
     * Sets the value of the refTacke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefTacke(String value) {
        this.refTacke = value;
    }

}
