//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.24 at 06:27:21 PM CEST 
//


package gov.gradskaskupstina;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TStav complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TStav">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Sadrzaj" type="{http://www.gradskaskupstina.gov/}TSemiStruktuiraniTekst"/>
 *         &lt;sequence>
 *           &lt;element name="Predtekst" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="Tacka" type="{http://www.gradskaskupstina.gov/}TTacka" maxOccurs="unbounded" minOccurs="2"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStav", propOrder = {
    "sadrzaj",
    "predtekst",
    "tacka"
})
public class TStav {

    @XmlElement(name = "Sadrzaj")
    protected TSemiStruktuiraniTekst sadrzaj;
    @XmlElement(name = "Predtekst")
    protected String predtekst;
    @XmlElement(name = "Tacka")
    protected List<TTacka> tacka;

    /**
     * Gets the value of the sadrzaj property.
     * 
     * @return
     *     possible object is
     *     {@link TSemiStruktuiraniTekst }
     *     
     */
    public TSemiStruktuiraniTekst getSadrzaj() {
        return sadrzaj;
    }

    /**
     * Sets the value of the sadrzaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSemiStruktuiraniTekst }
     *     
     */
    public void setSadrzaj(TSemiStruktuiraniTekst value) {
        this.sadrzaj = value;
    }

    /**
     * Gets the value of the predtekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredtekst() {
        return predtekst;
    }

    /**
     * Sets the value of the predtekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredtekst(String value) {
        this.predtekst = value;
    }

    /**
     * Gets the value of the tacka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tacka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTacka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TTacka }
     * 
     * 
     */
    public List<TTacka> getTacka() {
        if (tacka == null) {
            tacka = new ArrayList<TTacka>();
        }
        return this.tacka;
    }

}
