//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 05:13:15 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.gradskaskupstina.gov/",xmlns = {@XmlNs(prefix = "", namespaceURI = "http://www.gradskaskupstina.gov/")}, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hello.entity.gov.gradskaskupstina;

import javax.xml.bind.annotation.XmlNs;